library(tidyverse)
data <- read.csv("/Users/anujabarin/Desktop/ML project folder/churnforrpart_numeric.csv", stringsAsFactors = FALSE)
str(data)
#data$gender_N <- as.numeric(factor(data$gender))
data$InternetService_N <- as.numeric(factor(data$InternetService))
data$Contract_N <- as.numeric(factor(data$Contract))
data$OnlineSecurity_N <- as.numeric(factor(data$OnlineSecurity))
data$OnlineBackup_N <- as.numeric(factor(data$OnlineBackup))
data$DeviceProtection_N <- as.numeric(factor(data$DeviceProtection))
data$TechSupport_N <- as.numeric(factor(data$TechSupport))
data$StreamingTV_N <- as.numeric(factor(data$StreamingTV))
data$StreamingMovies_N <- as.numeric(factor(data$StreamingMovies))
data$PaymentMethod_N <- as.numeric(factor(data$PaymentMethod))
data$InternetService_N <- factor(data$InternetService_N)
data$Contract_N <- factor(data$Contract_N)
data$OnlineSecurity_N <- factor(data$OnlineSecurity_N)
data$OnlineBackup_N <- factor(data$OnlineBackup_N)
data$DeviceProtection_N <- factor(data$DeviceProtection_N)
data$TechSupport_N <- factor(data$TechSupport_N)
data$StreamingTV_N <- factor(data$StreamingTV_N)
data$StreamingMovies_N <- factor(data$StreamingMovies_N)
data$PaymentMethod_N <- factor(data$PaymentMethod_N)

myroots <- rpart(Churn_N~InternetService_N+Contract_N+OnlineSecurity_N+OnlineBackup_N+DeviceProtection_N+TechSupport_N+StreamingTV_N+StreamingMovies_N+PaymentMethod_N+MonthlyCharges+TotalCharges+Tenure,data=data, method="class",cp=0.01)

fancyRpartPlot(myroots)
plotcp(myroots)
